name: Test Workflow

on: 
  workflow_dispatch:

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # use custom action to fetch payload from github for frontend
      