name: Pipeline Integration Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Local Code
        uses: actions/checkout@v4

      - name: Execute Native Action Container
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Confirm JSON Data Structure
        run: cat frontend/src/gh-data.json